name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🎉 New Golang Versions"
    labels:
      - "go-version"
  - title: "🪲 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
autolabeler:
  - label: "chore"
    files:
      - "*.md"
      - ".github/*"
    branch:
      - '/docs{0,1}\/.+/'
    title:
      - "/chore/i"
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "enhancement"
    branch:
      - '/feature\/.+/i'
  - label: "go-version"
    branch:
      - '/feature\/.+/i'
    files:
      - "plugins/go-build/share/go-build/*"
    body:
      - '/(add|support) go(lang)? [0-9]+\.[0-9]+(\.[0-9]+)?/i'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes since $PREVIOUS_TAG

  $CHANGES
