// Code generated by scripts/generate_embedded_lifecycle/main.go; DO NOT EDIT.
// This file is generated from the endoflife.date API at build time.
// To regenerate: make generate-embedded
//
// Generated from: https://endoflife.date/api/go.json
// Generated at: 2025-12-01T19:53:17Z

package lifecycle

// EmbeddedLifecycleData contains fallback lifecycle information for Go versions
// Generated at build time from the endoflife.date API
// Used as last resort when both network and cache are unavailable
var EmbeddedLifecycleData = map[string]VersionInfo{
	"1.25": {
		Version:      "1.25",
		ReleaseDate:  parseDate("2025-08-12"),
		EOLDate:      parseDate("2099-12-31"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
	"1.24": {
		Version:      "1.24",
		ReleaseDate:  parseDate("2025-02-11"),
		EOLDate:      parseDate("2099-12-31"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
	"1.23": {
		Version:      "1.23",
		ReleaseDate:  parseDate("2024-08-13"),
		EOLDate:      parseDate("2025-08-12"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
	"1.22": {
		Version:      "1.22",
		ReleaseDate:  parseDate("2024-02-06"),
		EOLDate:      parseDate("2025-02-11"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
	"1.21": {
		Version:      "1.21",
		ReleaseDate:  parseDate("2023-08-08"),
		EOLDate:      parseDate("2024-08-13"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
	"1.20": {
		Version:      "1.20",
		ReleaseDate:  parseDate("2023-02-01"),
		EOLDate:      parseDate("2024-02-06"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
	"1.19": {
		Version:      "1.19",
		ReleaseDate:  parseDate("2022-08-02"),
		EOLDate:      parseDate("2023-09-06"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
	"1.18": {
		Version:      "1.18",
		ReleaseDate:  parseDate("2022-03-15"),
		EOLDate:      parseDate("2023-02-01"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
	"1.17": {
		Version:      "1.17",
		ReleaseDate:  parseDate("2021-08-16"),
		EOLDate:      parseDate("2022-08-02"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
	"1.16": {
		Version:      "1.16",
		ReleaseDate:  parseDate("2021-02-16"),
		EOLDate:      parseDate("2022-03-15"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
	"1.15": {
		Version:      "1.15",
		ReleaseDate:  parseDate("2020-08-11"),
		EOLDate:      parseDate("2021-08-16"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
	"1.14": {
		Version:      "1.14",
		ReleaseDate:  parseDate("2020-02-25"),
		EOLDate:      parseDate("2021-02-16"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
	"1.13": {
		Version:      "1.13",
		ReleaseDate:  parseDate("2019-09-03"),
		EOLDate:      parseDate("2020-08-11"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
	"1.12": {
		Version:      "1.12",
		ReleaseDate:  parseDate("2019-02-25"),
		EOLDate:      parseDate("2020-02-25"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
	"1.11": {
		Version:      "1.11",
		ReleaseDate:  parseDate("2018-08-24"),
		EOLDate:      parseDate("2019-09-03"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
	"1.10": {
		Version:      "1.10",
		ReleaseDate:  parseDate("2018-02-16"),
		EOLDate:      parseDate("2019-02-25"),
		Status:       StatusUnknown, // Calculated dynamically at runtime
		Recommended:  "",            // Calculated dynamically at runtime
		SecurityOnly: false,         // Determined at runtime
	},
}

// EmbeddedGeneratedAt is the timestamp when this file was generated
const EmbeddedGeneratedAt = "2025-12-01T19:53:17Z"
