#!/usr/bin/env bash
# Summary: Display the version
#
# Displays the version number of this release

set -e
[ -n "$GOENV_DEBUG" ] && set -x

base_dir=$(echo $(dirname -- "$0") | sed -E 's/goenv(\/[0-9]+\.[0-9]+\.[0-9]+|\/goenv)?.+/goenv\/\1/i')
base_dir=$(echo $base_dir | sed -E 's/\/$//')

version="$(cat $base_dir/APP_VERSION)"

echo "goenv ${version}"
