#!/usr/bin/env bash
# Summary: Reads specified version file if it exists
# Usage: goenv version-file-read <file>
set -e
[ -n "$GOENV_DEBUG" ] && set -x

VERSION_FILE="$1"

if [ ! -f "$VERSION_FILE" ]; then
  exit 1
fi

# NOTE: Read the first non-whitespace word from the specified version file.
# Be careful not to load it whole in case there's something crazy in it.
IFS="${IFS}"$'\r'
words=($(cut -b 1-1024 "$VERSION_FILE" | sed 's/^\s*\(\S\+\).*/\1/'))
versions=("${words[@]}")

if [ ! -n "$versions" ]; then
  exit 1
fi

IFS=":"
echo "${versions[*]}"
exit
