#!/usr/bin/env bash
# Summary: Show the current Go version
# Usage: goenv version-name
set -e
[ -n "$GOENV_DEBUG" ] && set -x

if [ -z "$GOENV_VERSION" ]; then
  GOENV_VERSION_FILE="$(goenv-version-file)"
  GOENV_VERSION="$(goenv-version-file-read "$GOENV_VERSION_FILE" || true)"
fi

OLDIFS="$IFS"
IFS=$'\n' scripts=(`goenv-hooks version-name`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -z "$GOENV_VERSION" ] || [ "$GOENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${GOENV_ROOT}/versions/${version}" ]
}

versions=()
OLDIFS="$IFS"
{
  IFS=:
  any_not_installed=0
  for version in ${GOENV_VERSION}; do
    if version_exists "$version" || [ "$version" = "system" ]; then
      versions=("${versions[@]}" "${version}")
    elif version_exists "${version#go-}"; then
      versions=("${versions[@]}" "${version#go-}")
    else
      echo "goenv: version '$version' is not installed (set by $(goenv-version-origin))" >&2
      any_not_installed=1
    fi
  done
}
IFS="$OLDIFS"

OLDIFS="$IFS"
{
  IFS=:
  echo "${versions[*]}"
}
IFS="$OLDIFS"

if [ "$any_not_installed" = 1 ]; then
  exit 1
fi
