#!/usr/bin/env bash
# Summary: Display the version
#
# Displays the version number of this release

set -e
[ -n "$GOENV_DEBUG" ] && set -x

base_dir=$(echo $(dirname -- "$0") | sed -E 's/goenv(\/[0-9]+\.[0-9]+\.[0-9]+)?.+/goenv\/\1/i')

version="$(cat ${base_dir}VERSION)"

echo "goenv ${version}"
